apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "kube-proxy.labels" . | indent 4 }}
  name: {{ template "kube-proxy.clusterRoleBindingName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-proxier
subjects:
- kind: ServiceAccount
  name: {{ template "kube-proxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
