{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-proxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "kube-proxy.labels" . | indent 4 }}
{{- end -}}

